"""Generates the machine-verified frontend dependency closure table for
THIRD-PARTY-LICENSES.md. Manual auditing of a 300+ package npm tree
proved unreliable (verified live: two hand-curated passes each missed
real packages) — this reads the actual resolved dependency tree via
license-checker instead of guessing from a minified bundle.

Usage (from frontend/):
    bunx license-checker --production --json --excludePackages "stlvault@<version>" > /path/to/licenses-raw.json
    ../backend/.venv/Scripts/python.exe scripts/generate-license-report.py /path/to/licenses-raw.json /path/to/output.md

Writes a markdown table to the given output path (explicit UTF-8 — see
the note near the bottom of this file about why that matters on
Windows), or stdout if no output path is given. Re-run this whenever frontend
dependencies change and paste the output into THIRD-PARTY-LICENSES.md's
"Full frontend production dependency closure" section, replacing what's
there — this is intentionally not wired into build.ps1 automatically,
since the license document should be reviewed by a human before ship,
not silently regenerated on every build.
"""
import json
import sys

# License-checker reports some packages as an SPDX OR-expression, meaning
# the package may be used under any one of the listed licenses. Resolve
# each to whichever option this document already carries a full text
# section for, preferring the most permissive/simplest first.
OR_PREFERENCE = ["MIT", "BSD-3-Clause", "Apache-2.0", "ISC", "BSD-2-Clause", "CC0-1.0", "WTFPL"]

# Packages whose license-checker classification needs a manual note
# rather than blind resolution (e.g. an AND-expression, or a package
# that's actually the project root and must be excluded).
SPECIAL_CASES = {
    "pako": "MIT (own LICENSE file is pure MIT; license-checker also associates a Zlib designation given pako's zlib-porting heritage — see the zlib note elsewhere in this document)",
}


def resolve_license(pkg_at_version: str, raw: str) -> str:
    raw = raw.strip()
    if raw == "UNKNOWN" or not raw:
        print(f"WARNING: {pkg_at_version} has no detectable license ({raw!r}) — "
              f"resolve this manually before shipping the generated table", file=sys.stderr)
        return raw
    if raw.startswith("(") and raw.endswith(")"):
        raw = raw[1:-1]
    if " AND " in raw:
        print(f"WARNING: {pkg_at_version} has an AND-expression license ({raw!r}) not in "
              f"SPECIAL_CASES — both terms apply simultaneously and this needs a manual "
              f"decision, not the OR-preference resolver", file=sys.stderr)
        return raw
    if " OR " in raw:
        options = [o.strip() for o in raw.split(" OR ")]
        for pref in OR_PREFERENCE:
            if pref in options:
                return f"{pref} (dual/multi-licensed: {raw} — used under the {pref} option)"
        print(f"WARNING: {pkg_at_version} offers only licenses this document has no "
              f"preference for ({raw!r}) — add one to OR_PREFERENCE or handle manually", file=sys.stderr)
        return raw
    if raw.endswith("*"):
        return f"{raw[:-1]} (license-checker inferred this from package metadata rather than an explicit license field)"
    return raw


def main():
    if len(sys.argv) not in (2, 3):
        print("Usage: generate-license-report.py <path-to-license-checker-json> [output-path]", file=sys.stderr)
        sys.exit(1)

    with open(sys.argv[1], encoding="utf-8") as f:
        data = json.load(f)

    rows = []
    for pkg_at_version, info in data.items():
        name, _, version = pkg_at_version.rpartition("@")
        if name in ("stlvault", ""):
            continue  # the project's own root package.json entry, not a real dependency
        # SPECIAL_CASES keys are always the full package name (including any
        # @scope/ prefix) — no separate "base name" extraction, since that
        # previously took the scope instead of the name for scoped packages
        # (e.g. "@emotion/react" -> "@emotion", not "react") and would have
        # silently matched the wrong package for any future scoped special case.
        if name in SPECIAL_CASES:
            license_display = SPECIAL_CASES[name]
        else:
            license_display = resolve_license(pkg_at_version, info.get("licenses", "UNKNOWN"))
        rows.append((name, version, license_display))

    rows.sort(key=lambda r: r[0].lower())

    lines = [
        f"<!-- Generated by frontend/scripts/generate-license-report.py — {len(rows)} packages -->",
        "| Package | Version | License |",
        "|---|---|---|",
    ]
    for name, version, license_display in rows:
        lines.append(f"| {name} | {version} | {license_display} |")

    # Written directly with explicit UTF-8 rather than printed to stdout —
    # a shell redirect (`> file.md`) on Windows can silently pick a
    # non-UTF-8 codepage for the em dashes this script emits, corrupting
    # the file without any visible error until something tries to read it
    # back as UTF-8 (confirmed live: this exact failure happened once).
    out_path = sys.argv[2] if len(sys.argv) > 2 else None
    text = "\n".join(lines) + "\n"
    if out_path:
        # newline="\n" pins LF output even on Windows (Python's default
        # text-mode write would translate to CRLF here), matching
        # THIRD-PARTY-LICENSES.md's own line endings so a paste-in never
        # flips 340+ lines' endings for no reason.
        with open(out_path, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
    else:
        sys.stdout.buffer.write(text.encode("utf-8"))


if __name__ == "__main__":
    main()
